import os, json, shutil

from idmtools.assets import Asset
from idmtools.core.platform_factory import Platform
from idmtools.entities.experiment import Experiment

from emodpy.emod_task import EMODTask

import emodpy_covid.microstructure.change_ser_pop as change_serialized_population

CANNED_DEMOGRAPHICS_FILENAME = "demographics.json"
CANNED_STATEFILE_FILENAME = "state-00000.dtk"
TEST_results = "TEST_results.txt"
from globals_zero_group import ERADICATION_PATH, SIM_CONFIG_PATH, SPOPS_ROOT

INPUTS_CANNED_DEMOGRAPHICS = os.path.join(
    SIM_CONFIG_PATH,
    CANNED_DEMOGRAPHICS_FILENAME
)
INPUTS_CANNED_STATEFILE = os.path.join(
    SIM_CONFIG_PATH,
    CANNED_STATEFILE_FILENAME
)

FINAL_DEMOGRAPHICS_FILENAME = 'demographics-microstructure.json'
FINAL_STATEFILE_FULLNAME = 'state-microstructure.dtk'


def add_microstructure_to_statefile_and_demographics(
        starting_statefile_fullpath,
        starting_demographics_fullpath
):
    change_serialized_population.change_ser_pop(
        path=starting_statefile_fullpath,
        input_demog=starting_demographics_fullpath,
        output_demog=FINAL_DEMOGRAPHICS_FILENAME,
        save_file_path=FINAL_STATEFILE_FULLNAME,
        use_singles_node=True
    )


if __name__ == "__main__":
    with open(TEST_results, "a") as test_results:
        test_results.write("Running ZeroGroupTest microstructure_01 script:\n")
        if not os.path.isfile(INPUTS_CANNED_DEMOGRAPHICS):
            test_results.write("ERROR: Could not find demographics file generated by microstructure_00. "
                              "You need to run it first.\n")
            raise EnvironmentError("You need to run microstructure_00 first\n")
        if not os.path.isfile(INPUTS_CANNED_STATEFILE):
            found_statefile = os.path.join(SPOPS_ROOT, CANNED_STATEFILE_FILENAME)
            if os.path.isfile(found_statefile):
                shutil.move(found_statefile, INPUTS_CANNED_STATEFILE)
            else:
                test_results.write("ERROR: Couldn't find statefile(*.dtk) either in inputs or in local folder.\n")
                raise EnvironmentError("Couldn't find statefile either in inputs or in local folder\n")
        add_microstructure_to_statefile_and_demographics(
            starting_statefile_fullpath=INPUTS_CANNED_STATEFILE,
            starting_demographics_fullpath=INPUTS_CANNED_DEMOGRAPHICS
        )

        if os.path.isfile(FINAL_DEMOGRAPHICS_FILENAME) and os.path.isfile(FINAL_DEMOGRAPHICS_FILENAME):
            test_results.write("GOOD: microstructure files generated successfully. \n ")

    pass
